[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.1.0"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.9.0"

[prune]
  go-tests = true
  unused-packages = true
